"""add user model and relationship

Revision ID: b5d9812c51f5
Revises: 1a2767b3bcb7
Create Date: 2025-01-20 17:47:46.599513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5d9812c51f5'
down_revision = '1a2767b3bcb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('recipient', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('express_shipping')
        batch_op.drop_column('sender_name')
        batch_op.drop_column('recipient_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('sender_name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('express_shipping', sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('location')
        batch_op.drop_column('recipient')
        batch_op.drop_column('sender')

    op.drop_table('users')
    # ### end Alembic commands ###
